language: emacs-lisp

env:
  matrix:
    - EMACS=emacs-snapshot

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
install:
  - if [ "$EMACS" = "emacs24" ]; then
      sudo apt-get install -qq emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
    fi
  - ln -s `pwd` ~/.emacs.d
script:
  $EMACS --version && make test EMACS=${EMACS}

notifications:
  email: false
